# Generated by Django 6.0.2 on 2026-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='serie',
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativa_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativa_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativa_c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativa_d',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.CharField(max_length=255),
        ),
    ]
