# Generated by Django 6.0.3 on 2026-03-31 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_align_pergunta_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('solo', 'Solo')], default='solo', max_length=20)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('abandonada', 'Abandonada')], default='em_andamento', max_length=20)),
                ('total_perguntas', models.PositiveSmallIntegerField(default=20)),
                ('pontuacao_total', models.PositiveIntegerField(default=0)),
                ('acertos', models.PositiveSmallIntegerField(default=0)),
                ('erros', models.PositiveSmallIntegerField(default=0)),
                ('pulo_usado', models.BooleanField(default=False)),
                ('eliminar_usado', models.BooleanField(default=False)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pergunta', models.PositiveSmallIntegerField()),
                ('pergunta_texto', models.TextField()),
                ('materia', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('resposta_marcada', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('resposta_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('acertou', models.BooleanField(default=False)),
                ('ajuda_utilizada', models.BooleanField(default=False)),
                ('ajudas_utilizadas', models.CharField(blank=True, max_length=50)),
                ('valor_pergunta', models.PositiveSmallIntegerField(default=10)),
                ('pontos_recebidos', models.PositiveSmallIntegerField(default=0)),
                ('respondida_em', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='quiz.partida')),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_partida', to='quiz.pergunta')),
            ],
            options={
                'ordering': ['numero_pergunta', 'id'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'numero_pergunta'), name='unique_resposta_por_ordem_na_partida')],
            },
        ),
    ]
