# Generated by Django 6.0.3 on 2026-04-24 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_slug', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moeda', models.CharField(default='BRL', max_length=10)),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='criada', max_length=20)),
                ('external_reference', models.CharField(default=uuid.uuid4, editable=False, max_length=80, unique=True)),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=120)),
                ('mercadopago_payment_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('status_detalhe', models.CharField(blank=True, max_length=120)),
                ('payment_type_id', models.CharField(blank=True, max_length=50)),
                ('retorno_payload', models.JSONField(blank=True, default=dict)),
                ('notificacao_payload', models.JSONField(blank=True, default=dict)),
                ('pagamento_payload', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('aprovada_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_tema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra de tema',
                'verbose_name_plural': 'Compras de temas',
                'ordering': ['-criada_em'],
            },
        ),
    ]
