# Generated by Django 6.0.3 on 2026-04-24 12:49

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_compratema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compratema',
            name='external_reference',
            field=models.CharField(default=quiz.models.gerar_external_reference, editable=False, max_length=80, unique=True),
        ),
    ]
