# Generated by Django 6.0.3 on 2026-05-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_compratema_external_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompraTema',
        ),
    ]
