# Generated by Django 6.0.3 on 2026-08-11 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_delete_compratema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaKahoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('titulo', models.CharField(default='Sala Kahoot', max_length=120)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='aguardando', max_length=20)),
                ('total_rodadas', models.PositiveSmallIntegerField(default=10)),
                ('rodada_atual', models.PositiveSmallIntegerField(default=0)),
                ('tempo_por_rodada', models.PositiveSmallIntegerField(default=20)),
                ('pergunta_iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('perguntas_sorteadas', models.JSONField(blank=True, default=list)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('anfitriao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_kahoot_criadas', to=settings.AUTH_USER_MODEL)),
                ('pergunta_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_kahoot_ativas', to='quiz.pergunta')),
            ],
            options={
                'verbose_name': 'Sala Kahoot',
                'verbose_name_plural': 'Salas Kahoot',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteSalaKahoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=80)),
                ('pontuacao_total', models.PositiveIntegerField(default=0)),
                ('respostas_certas', models.PositiveSmallIntegerField(default=0)),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_kahoot', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='quiz.salakahoot')),
            ],
            options={
                'verbose_name': 'Participante da sala Kahoot',
                'verbose_name_plural': 'Participantes das salas Kahoot',
                'ordering': ['-pontuacao_total', '-respostas_certas', 'apelido'],
            },
        ),
        migrations.CreateModel(
            name='RespostaSalaKahoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveSmallIntegerField()),
                ('resposta_marcada', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('resposta_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('acertou', models.BooleanField(default=False)),
                ('pontos_recebidos', models.PositiveIntegerField(default=0)),
                ('respondida_em', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='quiz.participantesalakahoot')),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_kahoot', to='quiz.pergunta')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='quiz.salakahoot')),
            ],
            options={
                'verbose_name': 'Resposta da sala Kahoot',
                'verbose_name_plural': 'Respostas das salas Kahoot',
                'ordering': ['rodada', 'respondida_em'],
                'constraints': [models.UniqueConstraint(fields=('participante', 'rodada'), name='unique_resposta_por_participante_e_rodada_kahoot')],
            },
        ),
        migrations.AddConstraint(
            model_name='participantesalakahoot',
            constraint=models.UniqueConstraint(fields=('sala', 'usuario'), name='unique_usuario_por_sala_kahoot'),
        ),
    ]
