# Generated by Django 6.0.3 on 2026-08-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_salakahoot_participantesalakahoot_respostasalakahoot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaSalaKahoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('alternativa_a', models.CharField(max_length=200)),
                ('alternativa_b', models.CharField(max_length=200)),
                ('alternativa_c', models.CharField(max_length=200)),
                ('alternativa_d', models.CharField(max_length=200)),
                ('alternativa_e', models.CharField(max_length=200)),
                ('resposta_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('serie', models.CharField(default='Personalizada', max_length=50)),
                ('materia', models.CharField(default='Sala', max_length=50)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_personalizadas', to='quiz.salakahoot')),
            ],
            options={
                'verbose_name': 'Pergunta personalizada da sala Kahoot',
                'verbose_name_plural': 'Perguntas personalizadas das salas Kahoot',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='salakahoot',
            name='pergunta_personalizada_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_kahoot_ativas', to='quiz.perguntasalakahoot'),
        ),
    ]
